version: "3.8"

services:
  keycloak:
    image: keycloak/keycloak:latest
    container_name: keycloak
    environment:
      - KC_DB=mysql
      - KC_DB_URL=jdbc:mysql://mysql:3306/keycloak
      - KC_DB_USERNAME=keycloak_user
      - KC_DB_PASSWORD=SecurePass123!
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=AdminPass123!
      - KC_HOSTNAME=localhost
      - KC_HTTP_ENABLED=true
      - KC_HEALTH_ENABLED=true
      - QUARKUS_HIBERNATE_ORM_PERSISTENCE_XML_IGNORE=true
    ports:
      - "8080:8080"
    command: start
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - keycloak-network

  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      - MYSQL_DATABASE=keycloak
      - MYSQL_USER=keycloak_user
      - MYSQL_PASSWORD=SecurePass123!
      - MYSQL_ROOT_PASSWORD=Manh2004
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pRootPass123!"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - keycloak-network

volumes:
  mysql_data:

networks:
  keycloak-network:
    driver: bridge