server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3307/book
    username: root
    password: Manh2004
  jpa:
    hibernate:
      ddl-auto: update
    #      none, update, auto-update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        enable_lazy_load_no_trans: true
        format_sql: true
    show-sql: true

  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: keycloak
            client-secret: 7nGn5k8SFb6Ybg0tOwgsFfxy9EuC76TT
            scope:
              - openid
              - email
              - profile
            authorization-grant-type:
              - authorization_code
            redirect-uri: http://localhost:8081/login/oauth2/code/keycloak
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/my-realm
      resource server:
        jwt:
          issuer-uri: http://localhost:8080/realms/my-realm
secretKey: ueKZ88pnk6JJSaiu8IqMPURPjcw04HF4gI/MiyH1cbA=
